nome: principal

em: [empurrar]

empregos:
  teste:
    em funcionamento: ubuntu-mais recente

    passos:
      - usos: ações/checkout@v2
      - usos: ações/node@v2 de configuração
        com:
          cache: fio
          versão de nó: 16
      - executar: instalar fios --arquivo de bloqueio congelado

      - executar: tipo de fio
      - corrida: fiapos de fio
      - executar: teste de fio --ci

  ação de teste:
    em funcionamento: ubuntu-mais recente
    passos:
      - usos: ações/checkout@v2

      - nome: atualizar action.yml para usar imagem do Dockerfile local
        corrida: |
          sed -i "s/image: .*/image: Dockerfile/" action.yml
      - nome: gerar-cobra-jogo-de-github-taxa de contribuição
        id: gerar cobra
        usos: ./
        com:
          rd-santos0: platano
          saídas: |
 dist/github-contribuição-grade-cobra.svg
 dist/github-contribuição-grade-cobra-escura.svg?paleta=github-escuro
 dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff.#64a1f4.#4b91f1.#3c7dd9
      - nome: certifique-se de que o arquivo gerado existe
        corrida: |
 Ls dist
 teste -f dist/github-contribuição-grade-cobra.svg
 teste -f dist/github-contribuição-grade-cobra-escura.svg
 teste -f dist/github-contribuição-grade-cobra.gif
      - usos: crazy-max/ghaction-github-pages@v2.5.0
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}

  implantação-ghpages:
    em funcionamento: ubuntu-mais recente
    passos:
      - usos: ações/checkout@v2
      - usos: ações/node@v2 de configuração
        com:
          cache: fio
          versão de nó: 16
      - executar: instalar fios --arquivo de bloqueio congelado

      - executar: construção de fios:demonstração
        env:
          GITHUB_USER_CONTRIBUTION_API_ENDPOINT: https://snk-one.vercel.app/api/github-user-contribution/

      - usos: crazy-max/ghaction-github-pages@v2.6.0
        se: sucesso() && github.ref == 'refs/heads/main'
        com:
          target_branch: gh-pages
          build_dir: pacotes/demonstração/dist
        env:
          GITHUB_TOKEN: ${{ segredos. MY_GITHUB_TOKEN_GH_PAGES }}
